### ISSUE TITLE
Update CMake configuration

### ISSUE THREAD

**Issue by HealthyPear** [jimbraun/XCDF#103]
- [ ] require a more recent version of CMake (>3) (#105)

- [x] require at least C++ 11 compilation (#104)

Some people (a minority I hope) are still using ancient versions of GCC for which the C++11 standard (the minimum required here) was still supported experimentally.

We cannot support all the compilers of the last 10 years, and for the next release I propose to _at least_ require C+11 explicitly by updating the CMake configuration with 

```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)
```

We should probably start tracking (maybe in a separate issue) the progress towards an update of the code base to support more recent standards.

- [ ] review policies set to OLD (#105)

This is not best practice in modern CMake (>v3 that is) and policies (which exist to improve development, fix bugs and introduce new features) should not be put to OLD in favour of a more recent version and features of CMake.

-------------------

I am not an expert of CMake -  these are just the obvious points I see.
